version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
